version: '3.8'

services:
  # PostgreSQL 17
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: python_learn
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:admin@db/python_learn
      - PORT=5000
      - SECRET_KEY=f91350a45c716a81b11fe8780c213e6e
    ports:
      - "2010:5000"
    depends_on:
      - db
  # FastAPI бэкенд 2
  tasks:
    build:
      context: ./tasks
      dockerfile: Dockerfile
    ports:
      - "2009:8000" # <хост_порт>:<контейнер_порт>

  # React фронтенд
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "2008:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend # Простой depends_on, чтобы сервисы запустились раньше
      - tasks

volumes:
  postgres_data:
