version: '3.8'

services:
  # PostgreSQL 17
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: python_learn
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network

  # FastAPI бэкенд 1
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:admin@db:5432/python_learn
      - PORT=8000
    expose:
      - "8000"  # Доступно только внутри Docker-сети
    networks:
      - backend_network

  # FastAPI бэкенд 2
  tasks:
    build:
      context: ./tasks
      dockerfile: Dockerfile
    environment:
      - PORT=5000
    expose:
      - "5000"  # Доступно только внутри Docker-сети
    networks:
      - backend_network
  # React фронтенд
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://backend:8000
    ports:
      - "2010:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
      - tasks
    networks:
      - frontend_network
      - backend_network

networks:
  frontend_network:
  backend_network:

volumes:
  postgres_data: